//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.UI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open the documentation. Please ensure a web browser is installed. Details: {0}.
        /// </summary>
        public static string Msg_DocumentationOpenFailed {
            get {
                return ResourceManager.GetString("Msg_DocumentationOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed copying embedded resource: {0}.
        /// </summary>
        public static string Msg_FailedCopyingEmbeddedResource {
            get {
                return ResourceManager.GetString("Msg_FailedCopyingEmbeddedResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No updates currently available..
        /// </summary>
        public static string Msg_NoUpdatesAvailable {
            get {
                return ResourceManager.GetString("Msg_NoUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open release link: {0}.
        /// </summary>
        public static string Msg_ReleaseLinkOpenFailed {
            get {
                return ResourceManager.GetString("Msg_ReleaseLinkOpenFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource Extraction Warning.
        /// </summary>
        public static string Msg_ResourceExtractionWarningTitle {
            get {
                return ResourceManager.GetString("Msg_ResourceExtractionWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A new version of Servy is available. Do you want to download it?.
        /// </summary>
        public static string Msg_UpdateAvailablePrompt {
            get {
                return ResourceManager.GetString("Msg_UpdateAvailablePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to check updates: {0}.
        /// </summary>
        public static string Msg_UpdateCheckFailed {
            get {
                return ResourceManager.GetString("Msg_UpdateCheckFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update check completed successfully, but the latest release identifier format could not be processed safely: &apos;{0}&apos;. Please inspect the project release page manually..
        /// </summary>
        public static string Msg_UpdateCheckInvalidTag {
            get {
                return ResourceManager.GetString("Msg_UpdateCheckInvalidTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The update check timed out. Please try again later..
        /// </summary>
        public static string Msg_UpdateCheckTimeout {
            get {
                return ResourceManager.GetString("Msg_UpdateCheckTimeout", resourceCulture);
            }
        }
    }
}
