<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.UI.IntegrationTests</AssemblyTitle>
    <Description>Servy.UI integration tests</Description>
    <Product>Servy.UI.IntegrationTests</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Servy.UI\Servy.UI.csproj" />
    <ProjectReference Include="..\Servy.Testing\Servy.Testing.csproj" />
  </ItemGroup>

</Project>
