<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
    <InvariantGlobalization>true</InvariantGlobalization>

    <IsTrimmable>true</IsTrimmable>
    <PublishTrimmed>true</PublishTrimmed>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <TrimMode>partial</TrimMode>
    <PublishReadyToRun>false</PublishReadyToRun>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>

    <DebuggerSupport>true</DebuggerSupport>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <CopyOutputSymbolsToPublishDirectory>true</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="System.Threading.Thread" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.Service</AssemblyTitle>
    <Description>Servy Wrapper Windows Service</Description>
    <Product>Servy.Service</Product>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\Servy.Restarter.exe" />
    <None Remove="Resources\Servy.Restarter.pdb" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.service.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\Servy.Restarter.exe" />
    <EmbeddedResource Include="Resources\Servy.Restarter.pdb" />
  </ItemGroup>

  <ItemGroup>
    <!-- Always include the shared base preserves -->
    <TrimmerRootDescriptor Include="..\linker.shared.xml" />

    <!-- Include project-specific preserves if the file exists in the project directory -->
    <TrimmerRootDescriptor Include="linker.xml" Condition="Exists('linker.xml')" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Servy.Service.UnitTests" />
    <InternalsVisibleTo Include="Servy.Service.IntegrationTests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="System.ServiceProcess.ServiceController" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Servy.Core\Servy.Core.csproj" />
    <ProjectReference Include="..\Servy.Infrastructure\Servy.Infrastructure.csproj" />
  </ItemGroup>

</Project>
