<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.UnitTests</AssemblyTitle>
    <Description>Servy unit tests</Description>
    <Product>Servy.UnitTests</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Servy.Core\Servy.Core.csproj" />
    <ProjectReference Include="..\..\src\Servy.UI\Servy.UI.csproj" />
    <ProjectReference Include="..\..\src\Servy\Servy.csproj" />
    <ProjectReference Include="..\Servy.Testing\Servy.Testing.csproj" />
  </ItemGroup>

</Project>
