<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.Infrastructure</AssemblyTitle>
    <Description>Data access, persistence, and integration with external systems (e.g., SQLite database, configuration files)</Description>
    <Product>Servy.Infrastructure</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="ConfigureAwait.Fody" PrivateAssets="All" />
    <PackageReference Include="Dapper" />
    <PackageReference Include="SourceGear.sqlite3" />
    <PackageReference Include="System.Data.SQLite" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Servy.Core\Servy.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Servy.Infrastructure.UnitTests" />
    <InternalsVisibleTo Include="Servy.Infrastructure.IntegrationTests" />
  </ItemGroup>
  
</Project>
