<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <IsTestProject>false</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.Testing</AssemblyTitle>
    <Description>Shared testing utilities</Description>
    <Product>Servy.Testing</Product>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\handle64.exe" />
    <None Remove="Resources\handle64a.exe" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\handle64.exe" />
    <EmbeddedResource Include="Resources\handle64a.exe" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.extensibility.core" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Servy.CLI\Servy.CLI.csproj" />
    <ProjectReference Include="..\..\src\Servy.Core\Servy.Core.csproj" />
  </ItemGroup>

</Project>
