<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
    <InvariantGlobalization>true</InvariantGlobalization>

    <IsTrimmable>true</IsTrimmable>
    <PublishTrimmed>true</PublishTrimmed>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <TrimMode>partial</TrimMode>
    <PublishReadyToRun>false</PublishReadyToRun>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>

    <DebuggerSupport>true</DebuggerSupport>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <CopyOutputSymbolsToPublishDirectory>true</CopyOutputSymbolsToPublishDirectory>
  </PropertyGroup>

  <ItemGroup>
    <TrimmerRootAssembly Include="System.Threading.Thread" />
  </ItemGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.CLI</AssemblyTitle>
    <Description>Servy Command Line Interface</Description>
    <Product>Servy.CLI</Product>
    <ApplicationIcon>servy.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\handle64.exe" />
    <None Remove="Resources\handle64a.exe" />
    <None Remove="Resources\Servy.Service.CLI.exe" />
    <None Remove="Resources\Servy.Service.CLI.pdb" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\handle64.exe" />
    <EmbeddedResource Include="Resources\handle64a.exe" />
    <EmbeddedResource Include="Resources\Servy.Service.CLI.exe" />
    <EmbeddedResource Include="Resources\Servy.Service.CLI.pdb" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.cli.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="servy.ico" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Servy.CLI.UnitTests" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Strings.Designer.cs">
      <DependentUpon>Strings.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.resx">
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <!-- Always include the shared base preserves -->
    <TrimmerRootDescriptor Include="..\linker.shared.xml" />

    <!-- Include project-specific preserves if the file exists in the project directory -->
    <TrimmerRootDescriptor Include="linker.xml" Condition="Exists('linker.xml')" />
  </ItemGroup>


  <ItemGroup>
    <PackageReference Include="CommandLineParser" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Newtonsoft.Json" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Servy.Core\Servy.Core.csproj" />
    <ProjectReference Include="..\Servy.Infrastructure\Servy.Infrastructure.csproj" />
  </ItemGroup>

</Project>
