<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.Manager.UnitTests</AssemblyTitle>
    <Description>Servy.Manager unit tests</Description>
    <Product>Servy.Manager.UnitTests</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Servy.Core\Servy.Core.csproj" />
    <ProjectReference Include="..\..\src\Servy.Manager\Servy.Manager.csproj" />
    <ProjectReference Include="..\..\src\Servy.UI\Servy.UI.csproj" />
    <ProjectReference Include="..\Servy.Testing\Servy.Testing.csproj" />
  </ItemGroup>

</Project>
