<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.Restarter.UnitTests</AssemblyTitle>
    <Description>Servy.Restarter unit tests</Description>
    <Product>Servy.Restarter.UnitTests</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Servy.Restarter\Servy.Restarter.csproj" />
    <ProjectReference Include="..\Servy.Testing\Servy.Testing.csproj" />
  </ItemGroup>

</Project>
