//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.CLI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.CLI.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Denied. Please restart your shell as Administrator to run the &apos;{0}&apos; command..
        /// </summary>
        public static string Msg_AdminPrivilegesRequired {
            get {
                return ResourceManager.GetString("Msg_AdminPrivilegesRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation &apos;{0}&apos; was cancelled by the user..
        /// </summary>
        public static string Msg_CommandCancelled {
            get {
                return ResourceManager.GetString("Msg_CommandCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0}: {1}.
        /// </summary>
        public static string Msg_CommandFailedTemplate {
            get {
                return ResourceManager.GetString("Msg_CommandFailedTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file type is required (XML or JSON)..
        /// </summary>
        public static string Msg_ConfigFileTypeRequired {
            get {
                return ResourceManager.GetString("Msg_ConfigFileTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to export configuration for service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_ExportServiceAction {
            get {
                return ResourceManager.GetString("Msg_ExportServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the service exists in the database and you have write permissions to the destination path..
        /// </summary>
        public static string Msg_ExportServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_ExportServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configuration exported successfully to: {1}.
        /// </summary>
        public static string Msg_ExportSuccess {
            get {
                return ResourceManager.GetString("Msg_ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize the service configuration. Nothing was imported..
        /// </summary>
        public static string Msg_ImportDeserializationFailure {
            get {
                return ResourceManager.GetString("Msg_ImportDeserializationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} file is not valid: {1}.
        /// </summary>
        public static string Msg_ImportFormatInvalid {
            get {
                return ResourceManager.GetString("Msg_ImportFormatInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service configuration was saved, but installation failed for service &apos;{0}&apos;..
        /// </summary>
        public static string Msg_ImportInstallGeneralFailure {
            get {
                return ResourceManager.GetString("Msg_ImportInstallGeneralFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service configuration was saved, but the service &apos;{0}&apos; could not be located for installation..
        /// </summary>
        public static string Msg_ImportInstallLookupFailure {
            get {
                return ResourceManager.GetString("Msg_ImportInstallLookupFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configuration saved and service &apos;{1}&apos; installed successfully..
        /// </summary>
        public static string Msg_ImportInstallSuccess {
            get {
                return ResourceManager.GetString("Msg_ImportInstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import {0} configuration into the repository..
        /// </summary>
        public static string Msg_ImportRepoFailure {
            get {
                return ResourceManager.GetString("Msg_ImportRepoFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to import configuration from &apos;{0}&apos;.
        /// </summary>
        public static string Msg_ImportServiceAction {
            get {
                return ResourceManager.GetString("Msg_ImportServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check that the file path is correct, the file format is valid JSON or XML, and you have read permissions..
        /// </summary>
        public static string Msg_ImportServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_ImportServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} configuration imported successfully..
        /// </summary>
        public static string Msg_ImportSuccessNoInstall {
            get {
                return ResourceManager.GetString("Msg_ImportSuccessNoInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to install service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_InstallServiceAction {
            get {
                return ResourceManager.GetString("Msg_InstallServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the executable path is correct, the service name is not already in use, and you are running with Administrator privileges..
        /// </summary>
        public static string Msg_InstallServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_InstallServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; installed successfully..
        /// </summary>
        public static string Msg_InstallSuccess {
            get {
                return ResourceManager.GetString("Msg_InstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value for {0}: &apos;{1}&apos;. Valid options: {2}.
        /// </summary>
        public static string Msg_InvalidEnumValue {
            get {
                return ResourceManager.GetString("Msg_InvalidEnumValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid executable path: {0}. Ensure the file exists and is accessible..
        /// </summary>
        public static string Msg_InvalidExecutablePath {
            get {
                return ResourceManager.GetString("Msg_InvalidExecutablePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid integer format for {0}: &apos;{1}&apos;.
        /// </summary>
        public static string Msg_InvalidIntegerFormat {
            get {
                return ResourceManager.GetString("Msg_InvalidIntegerFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0}.
        /// </summary>
        public static string Msg_LogFailed {
            get {
                return ResourceManager.GetString("Msg_LogFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0} (Unauthorized).
        /// </summary>
        public static string Msg_LogFailedUnauthorized {
            get {
                return ResourceManager.GetString("Msg_LogFailedUnauthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File path is required..
        /// </summary>
        public static string Msg_PathRequired {
            get {
                return ResourceManager.GetString("Msg_PathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: service operation completed successfully, but post-success repository synchronization failed for &apos;{1}&apos;: {2}.
        /// </summary>
        public static string Msg_PostSuccessSyncFailed {
            get {
                return ResourceManager.GetString("Msg_PostSuccessSyncFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preparing environment....
        /// </summary>
        public static string Msg_PreparingEnvironment {
            get {
                return ResourceManager.GetString("Msg_PreparingEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to restart service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_RestartServiceAction {
            get {
                return ResourceManager.GetString("Msg_RestartServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the service is currently installed and that your account has sufficient permissions to stop and start services..
        /// </summary>
        public static string Msg_RestartServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_RestartServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; restarted successfully..
        /// </summary>
        public static string Msg_RestartSuccess {
            get {
                return ResourceManager.GetString("Msg_RestartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified service is disabled..
        /// </summary>
        public static string Msg_ServiceDisabledError {
            get {
                return ResourceManager.GetString("Msg_ServiceDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}: failed to {1}: {2}.
        /// </summary>
        public static string Msg_ServiceOperationFailed {
            get {
                return ResourceManager.GetString("Msg_ServiceOperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query status for service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_ServiceStatusAction {
            get {
                return ResourceManager.GetString("Msg_ServiceStatusAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service status for &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Msg_ServiceStatusResult {
            get {
                return ResourceManager.GetString("Msg_ServiceStatusResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify the service name is spelled correctly and that it is currently installed on this system..
        /// </summary>
        public static string Msg_ServiceStatusSuggestion {
            get {
                return ResourceManager.GetString("Msg_ServiceStatusSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to start service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_StartServiceAction {
            get {
                return ResourceManager.GetString("Msg_StartServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the service is installed, the executable path is valid, and the service account has &apos;Log On As Service&apos; rights..
        /// </summary>
        public static string Msg_StartServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_StartServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; started successfully..
        /// </summary>
        public static string Msg_StartSuccess {
            get {
                return ResourceManager.GetString("Msg_StartSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stop service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_StopServiceAction {
            get {
                return ResourceManager.GetString("Msg_StopServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure you have Administrator privileges. If the service is unresponsive, you may need to terminate the process manually via Task Manager..
        /// </summary>
        public static string Msg_StopServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_StopServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; stopped successfully..
        /// </summary>
        public static string Msg_StopSuccess {
            get {
                return ResourceManager.GetString("Msg_StopSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion: {0}.
        /// </summary>
        public static string Msg_SuggestionTemplate {
            get {
                return ResourceManager.GetString("Msg_SuggestionTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to uninstall service &apos;{0}&apos;.
        /// </summary>
        public static string Msg_UninstallServiceAction {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; was not installed in Windows SCM; removed leftover database configuration..
        /// </summary>
        public static string Msg_UninstallServiceNotInstalled {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceNotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ensure the service is stopped before uninstalling and that you are running this command as an Administrator..
        /// </summary>
        public static string Msg_UninstallServiceSuggestion {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; uninstalled successfully..
        /// </summary>
        public static string Msg_UninstallSuccess {
            get {
                return ResourceManager.GetString("Msg_UninstallSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred..
        /// </summary>
        public static string Msg_UnknownError {
            get {
                return ResourceManager.GetString("Msg_UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported configuration file type: {0}.
        /// </summary>
        public static string Msg_UnsupportedFileType {
            get {
                return ResourceManager.GetString("Msg_UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrapper executable not found at: {0}. Ensure Servy is properly installed..
        /// </summary>
        public static string Msg_WrapperNotFound {
            get {
                return ResourceManager.GetString("Msg_WrapperNotFound", resourceCulture);
            }
        }
    }
}
