<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.Service.IntegrationTests</AssemblyTitle>
    <Description>Servy.Service integration tests</Description>
    <Product>Servy.Service.IntegrationTests</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
    <PackageReference Include="System.Management" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Servy.Service\Servy.Service.csproj" />
    <ProjectReference Include="..\Servy.Testing\Servy.Testing.csproj" />
  </ItemGroup>

</Project>
