//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.Manager.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.Manager.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays application information and copyright details..
        /// </summary>
        public static string Automation_AboutMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_AboutMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions Column.
        /// </summary>
        public static string Automation_ActionsColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_ActionsColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checks if a newer version of Servy is available..
        /// </summary>
        public static string Automation_CheckUpdatesMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_CheckUpdatesMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the configuration app for the selected service..
        /// </summary>
        public static string Automation_ConfigMenu_HelpText {
            get {
                return ResourceManager.GetString("Automation_ConfigMenu_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter text to filter the visible log lines..
        /// </summary>
        public static string Automation_ConsoleFilterTextBox_HelpText {
            get {
                return ResourceManager.GetString("Automation_ConsoleFilterTextBox_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Filter.
        /// </summary>
        public static string Automation_ConsoleFilterTextBox_Name {
            get {
                return ResourceManager.GetString("Automation_ConsoleFilterTextBox_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructions on how to configure stdout and stderr redirection for live console output..
        /// </summary>
        public static string Automation_ConsoleInstructions_HelpText {
            get {
                return ResourceManager.GetString("Automation_ConsoleInstructions_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Instructions.
        /// </summary>
        public static string Automation_ConsoleInstructions_Name {
            get {
                return ResourceManager.GetString("Automation_ConsoleInstructions_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays scrolling log output. Use context menu to copy selected lines..
        /// </summary>
        public static string Automation_ConsoleLogList_HelpText {
            get {
                return ResourceManager.GetString("Automation_ConsoleLogList_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Terminal.
        /// </summary>
        public static string Automation_ConsoleLogList_Name {
            get {
                return ResourceManager.GetString("Automation_ConsoleLogList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a service to view its console output..
        /// </summary>
        public static string Automation_ConsoleServiceList_HelpText {
            get {
                return ResourceManager.GetString("Automation_ConsoleServiceList_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Selector.
        /// </summary>
        public static string Automation_ConsoleServiceList_Name {
            get {
                return ResourceManager.GetString("Automation_ConsoleServiceList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the real-time standard output and error logs for the selected service..
        /// </summary>
        public static string Automation_ConsoleTab_HelpText {
            get {
                return ResourceManager.GetString("Automation_ConsoleTab_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Tab.
        /// </summary>
        public static string Automation_ConsoleTab_Name {
            get {
                return ResourceManager.GetString("Automation_ConsoleTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays real-time standard output and error logs for the selected service..
        /// </summary>
        public static string Automation_ConsoleViewRoot_HelpText {
            get {
                return ResourceManager.GetString("Automation_ConsoleViewRoot_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console Output View.
        /// </summary>
        public static string Automation_ConsoleViewRoot_Name {
            get {
                return ResourceManager.GetString("Automation_ConsoleViewRoot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies selected console log lines to the clipboard..
        /// </summary>
        public static string Automation_CopyLogMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_CopyLogMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Selection.
        /// </summary>
        public static string Automation_CopyLogMenuItem_Name {
            get {
                return ResourceManager.GetString("Automation_CopyLogMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the Process ID to the clipboard..
        /// </summary>
        public static string Automation_CopyPidButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_CopyPidButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current CPU usage of the service..
        /// </summary>
        public static string Automation_CpuColumnCell_HelpText {
            get {
                return ResourceManager.GetString("Automation_CpuColumnCell_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Column.
        /// </summary>
        public static string Automation_CpuColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_CpuColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical view of CPU percentage usage..
        /// </summary>
        public static string Automation_CpuGraphGrid_HelpText {
            get {
                return ResourceManager.GetString("Automation_CpuGraphGrid_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU Usage Graph.
        /// </summary>
        public static string Automation_CpuGraphGrid_Name {
            get {
                return ResourceManager.GetString("Automation_CpuGraphGrid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the real-time percentage of CPU utilized by the service process..
        /// </summary>
        public static string Automation_CpuUsageLabel_HelpText {
            get {
                return ResourceManager.GetString("Automation_CpuUsageLabel_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current CPU Usage.
        /// </summary>
        public static string Automation_CpuUsageLabel_Name {
            get {
                return ResourceManager.GetString("Automation_CpuUsageLabel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapses all branches in the dependency tree..
        /// </summary>
        public static string Automation_DependenciesCollapseAllButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesCollapseAllButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expands all branches in the dependency tree..
        /// </summary>
        public static string Automation_DependenciesExpandAllButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesExpandAllButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information on the service dependency tree mechanism via Windows Service Control Manager..
        /// </summary>
        public static string Automation_DependenciesLegendInfo_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesLegendInfo_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Legend Information.
        /// </summary>
        public static string Automation_DependenciesLegendInfo_Name {
            get {
                return ResourceManager.GetString("Automation_DependenciesLegendInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reloads the dependency tree for the selected service..
        /// </summary>
        public static string Automation_DependenciesRefreshButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesRefreshButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search and select a service to view its dependencies..
        /// </summary>
        public static string Automation_DependenciesServiceList_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesServiceList_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Selection List.
        /// </summary>
        public static string Automation_DependenciesServiceList_Name {
            get {
                return ResourceManager.GetString("Automation_DependenciesServiceList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that pressing F5 refreshes the dependency tree..
        /// </summary>
        public static string Automation_DependenciesShortcutInfo_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesShortcutInfo_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Information.
        /// </summary>
        public static string Automation_DependenciesShortcutInfo_Name {
            get {
                return ResourceManager.GetString("Automation_DependenciesShortcutInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows the service dependencies tree and status hierarchy..
        /// </summary>
        public static string Automation_DependenciesTab_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesTab_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies Tab.
        /// </summary>
        public static string Automation_DependenciesTab_Name {
            get {
                return ResourceManager.GetString("Automation_DependenciesTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays recursive dependencies for the selected service..
        /// </summary>
        public static string Automation_DependenciesTreeView_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesTreeView_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency Hierarchy Tree.
        /// </summary>
        public static string Automation_DependenciesTreeView_Name {
            get {
                return ResourceManager.GetString("Automation_DependenciesTreeView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Explains the status color indicators for tree nodes: green for running, red for stopped, orange for cycle..
        /// </summary>
        public static string Automation_DependenciesUsageInfo_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesUsageInfo_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Information.
        /// </summary>
        public static string Automation_DependenciesUsageInfo_Name {
            get {
                return ResourceManager.GetString("Automation_DependenciesUsageInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the service list and their hierarchical dependencies..
        /// </summary>
        public static string Automation_DependenciesViewRoot_HelpText {
            get {
                return ResourceManager.GetString("Automation_DependenciesViewRoot_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies View.
        /// </summary>
        public static string Automation_DependenciesViewRoot_Name {
            get {
                return ResourceManager.GetString("Automation_DependenciesViewRoot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The description of the service..
        /// </summary>
        public static string Automation_DescriptionColumnCell_HelpText {
            get {
                return ResourceManager.GetString("Automation_DescriptionColumnCell_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Column.
        /// </summary>
        public static string Automation_DescriptionColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_DescriptionColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the official Servy documentation..
        /// </summary>
        public static string Automation_DocMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_DocMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a menu containing documentation and update options..
        /// </summary>
        public static string Automation_HelpMenu_HelpText {
            get {
                return ResourceManager.GetString("Automation_HelpMenu_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports a service configuration from a JSON file..
        /// </summary>
        public static string Automation_ImportJsonMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_ImportJsonMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a menu to import service configurations..
        /// </summary>
        public static string Automation_ImportMenu_HelpText {
            get {
                return ResourceManager.GetString("Automation_ImportMenu_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports a service configuration from an XML file..
        /// </summary>
        public static string Automation_ImportXmlMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_ImportXmlMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays full message text and details for the selected log entry..
        /// </summary>
        public static string Automation_LogDetailsTextBox_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogDetailsTextBox_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Entry Details.
        /// </summary>
        public static string Automation_LogDetailsTextBox_Name {
            get {
                return ResourceManager.GetString("Automation_LogDetailsTextBox_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user account the service is running as..
        /// </summary>
        public static string Automation_LogOnAsColumnCell_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogOnAsColumnCell_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Session Column.
        /// </summary>
        public static string Automation_LogOnAsColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_LogOnAsColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the filtered list of diagnostic log entries..
        /// </summary>
        public static string Automation_LogsDataGrid_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsDataGrid_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Logs.
        /// </summary>
        public static string Automation_LogsDataGrid_Name {
            get {
                return ResourceManager.GetString("Automation_LogsDataGrid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows total count and query execution duration for current logs filter..
        /// </summary>
        public static string Automation_LogsFooterText_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsFooterText_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the start date to filter log entries from..
        /// </summary>
        public static string Automation_LogsFromDatePicker_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsFromDatePicker_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter from date.
        /// </summary>
        public static string Automation_LogsFromDatePicker_Name {
            get {
                return ResourceManager.GetString("Automation_LogsFromDatePicker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag to adjust the balance between log list and log message details pane..
        /// </summary>
        public static string Automation_LogsGridSplitter_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsGridSplitter_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Details Resizer.
        /// </summary>
        public static string Automation_LogsGridSplitter_Name {
            get {
                return ResourceManager.GetString("Automation_LogsGridSplitter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a keyword to search within log messages..
        /// </summary>
        public static string Automation_LogsKeywordTextBox_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsKeywordTextBox_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Keyword.
        /// </summary>
        public static string Automation_LogsKeywordTextBox_Name {
            get {
                return ResourceManager.GetString("Automation_LogsKeywordTextBox_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level Column.
        /// </summary>
        public static string Automation_LogsLevelColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_LogsLevelColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a log severity level to filter the displayed log entries..
        /// </summary>
        public static string Automation_LogsLevelComboBox_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsLevelComboBox_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter by Level.
        /// </summary>
        public static string Automation_LogsLevelComboBox_Name {
            get {
                return ResourceManager.GetString("Automation_LogsLevelComboBox_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Level Icon.
        /// </summary>
        public static string Automation_LogsLevelIcon_Name {
            get {
                return ResourceManager.GetString("Automation_LogsLevelIcon_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message Column.
        /// </summary>
        public static string Automation_LogsMessageColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_LogsMessageColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes the log search with current level, date, and keyword filters..
        /// </summary>
        public static string Automation_LogsSearchButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsSearchButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that pressing F5 refreshes logs..
        /// </summary>
        public static string Automation_LogsShortcutInfo_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsShortcutInfo_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shortcut Information.
        /// </summary>
        public static string Automation_LogsShortcutInfo_Name {
            get {
                return ResourceManager.GetString("Automation_LogsShortcutInfo_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a list of system events and diagnostic records for the service..
        /// </summary>
        public static string Automation_LogsTab_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsTab_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs Tab.
        /// </summary>
        public static string Automation_LogsTab_Name {
            get {
                return ResourceManager.GetString("Automation_LogsTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Column.
        /// </summary>
        public static string Automation_LogsTimeColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_LogsTimeColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the end date to filter log entries up to..
        /// </summary>
        public static string Automation_LogsToDatePicker_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsToDatePicker_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter to date.
        /// </summary>
        public static string Automation_LogsToDatePicker_Name {
            get {
                return ResourceManager.GetString("Automation_LogsToDatePicker_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a list of system events and diagnostic records for services..
        /// </summary>
        public static string Automation_LogsViewRoot_HelpText {
            get {
                return ResourceManager.GetString("Automation_LogsViewRoot_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs View.
        /// </summary>
        public static string Automation_LogsViewRoot_Name {
            get {
                return ResourceManager.GetString("Automation_LogsViewRoot_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the total number of services loaded and execution time..
        /// </summary>
        public static string Automation_MainFooterText_HelpText {
            get {
                return ResourceManager.GetString("Automation_MainFooterText_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provides options to import configuration, configure settings, and access help..
        /// </summary>
        public static string Automation_MainMenu_HelpText {
            get {
                return ResourceManager.GetString("Automation_MainMenu_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Menu.
        /// </summary>
        public static string Automation_MainMenu_Name {
            get {
                return ResourceManager.GetString("Automation_MainMenu_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicates that pressing F5 refreshes the service list..
        /// </summary>
        public static string Automation_MainShortcutInfo_HelpText {
            get {
                return ResourceManager.GetString("Automation_MainShortcutInfo_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the main list of managed services..
        /// </summary>
        public static string Automation_MainTab_HelpText {
            get {
                return ResourceManager.GetString("Automation_MainTab_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services Tab.
        /// </summary>
        public static string Automation_MainTab_Name {
            get {
                return ResourceManager.GetString("Automation_MainTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allows switching between Services, Performance, Console, Dependencies, and Logs views..
        /// </summary>
        public static string Automation_MainTabControl_HelpText {
            get {
                return ResourceManager.GetString("Automation_MainTabControl_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Navigation Tabs.
        /// </summary>
        public static string Automation_MainTabControl_Name {
            get {
                return ResourceManager.GetString("Automation_MainTabControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The main interface for the Servy service manager, used to configure service parameters and monitor execution..
        /// </summary>
        public static string Automation_MainWindow_HelpText {
            get {
                return ResourceManager.GetString("Automation_MainWindow_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servy Manager Window.
        /// </summary>
        public static string Automation_MainWindow_Name {
            get {
                return ResourceManager.GetString("Automation_MainWindow_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens a menu with additional actions for the current service..
        /// </summary>
        public static string Automation_MoreActionsButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_MoreActionsButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The name of the service..
        /// </summary>
        public static string Automation_NameColumnCell_HelpText {
            get {
                return ResourceManager.GetString("Automation_NameColumnCell_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Column.
        /// </summary>
        public static string Automation_NameColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_NameColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a service from the list to view its performance data..
        /// </summary>
        public static string Automation_PerformanceServiceList_HelpText {
            get {
                return ResourceManager.GetString("Automation_PerformanceServiceList_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Selector.
        /// </summary>
        public static string Automation_PerformanceServiceList_Name {
            get {
                return ResourceManager.GetString("Automation_PerformanceServiceList_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays real-time CPU and memory usage statistics for the running service..
        /// </summary>
        public static string Automation_PerformanceTab_HelpText {
            get {
                return ResourceManager.GetString("Automation_PerformanceTab_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Tab.
        /// </summary>
        public static string Automation_PerformanceTab_Name {
            get {
                return ResourceManager.GetString("Automation_PerformanceTab_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays resource usage statistics for the selected process..
        /// </summary>
        public static string Automation_PerformanceView_HelpText {
            get {
                return ResourceManager.GetString("Automation_PerformanceView_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance Monitor View.
        /// </summary>
        public static string Automation_PerformanceView_Name {
            get {
                return ResourceManager.GetString("Automation_PerformanceView_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The process identifier (PID) of the running service..
        /// </summary>
        public static string Automation_PidColumnCell_HelpText {
            get {
                return ResourceManager.GetString("Automation_PidColumnCell_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID Column.
        /// </summary>
        public static string Automation_PidColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_PidColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the Process ID of the currently selected service process..
        /// </summary>
        public static string Automation_PidValue_HelpText {
            get {
                return ResourceManager.GetString("Automation_PidValue_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process ID.
        /// </summary>
        public static string Automation_PidValue_Name {
            get {
                return ResourceManager.GetString("Automation_PidValue_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current RAM usage of the service..
        /// </summary>
        public static string Automation_RamColumnCell_HelpText {
            get {
                return ResourceManager.GetString("Automation_RamColumnCell_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM Column.
        /// </summary>
        public static string Automation_RamColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_RamColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historical view of memory usage..
        /// </summary>
        public static string Automation_RamGraphGrid_HelpText {
            get {
                return ResourceManager.GetString("Automation_RamGraphGrid_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM Usage Graph.
        /// </summary>
        public static string Automation_RamGraphGrid_Name {
            get {
                return ResourceManager.GetString("Automation_RamGraphGrid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays the real-time memory usage of the service process..
        /// </summary>
        public static string Automation_RamUsageLabel_HelpText {
            get {
                return ResourceManager.GetString("Automation_RamUsageLabel_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current RAM Usage.
        /// </summary>
        public static string Automation_RamUsageLabel_Name {
            get {
                return ResourceManager.GetString("Automation_RamUsageLabel_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarts all selected services..
        /// </summary>
        public static string Automation_RestartSelectedButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_RestartSelectedButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restarts the current service..
        /// </summary>
        public static string Automation_RestartServiceButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_RestartServiceButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Service.
        /// </summary>
        public static string Automation_RestartServiceButton_Name {
            get {
                return ResourceManager.GetString("Automation_RestartServiceButton_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resumes automatic scrolling to the latest log entry..
        /// </summary>
        public static string Automation_ResumeScrollButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_ResumeScrollButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume Scrolling.
        /// </summary>
        public static string Automation_ResumeScrollButton_Name {
            get {
                return ResourceManager.GetString("Automation_ResumeScrollButton_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the configuration app for this service..
        /// </summary>
        public static string Automation_RowConfigMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_RowConfigMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure Service.
        /// </summary>
        public static string Automation_RowConfigMenuItem_Name {
            get {
                return ResourceManager.GetString("Automation_RowConfigMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies the current Process ID of the service to the clipboard..
        /// </summary>
        public static string Automation_RowCopyPidMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_RowCopyPidMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports the current service configuration to a JSON file..
        /// </summary>
        public static string Automation_RowExportJsonMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_RowExportJsonMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports the current service configuration to an XML file..
        /// </summary>
        public static string Automation_RowExportXmlMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_RowExportXmlMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs the service configuration to the system..
        /// </summary>
        public static string Automation_RowInstallMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_RowInstallMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Service.
        /// </summary>
        public static string Automation_RowInstallMenuItem_Name {
            get {
                return ResourceManager.GetString("Automation_RowInstallMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the service from the Servy Manager list..
        /// </summary>
        public static string Automation_RowRemoveMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_RowRemoveMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Service.
        /// </summary>
        public static string Automation_RowRemoveMenuItem_Name {
            get {
                return ResourceManager.GetString("Automation_RowRemoveMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalls the service from the system..
        /// </summary>
        public static string Automation_RowUninstallMenuItem_HelpText {
            get {
                return ResourceManager.GetString("Automation_RowUninstallMenuItem_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall Service.
        /// </summary>
        public static string Automation_RowUninstallMenuItem_Name {
            get {
                return ResourceManager.GetString("Automation_RowUninstallMenuItem_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executes the service search..
        /// </summary>
        public static string Automation_SearchButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_SearchButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a keyword to filter the services list..
        /// </summary>
        public static string Automation_SearchTextBox_HelpText {
            get {
                return ResourceManager.GetString("Automation_SearchTextBox_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Services.
        /// </summary>
        public static string Automation_SearchTextBox_Name {
            get {
                return ResourceManager.GetString("Automation_SearchTextBox_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Services Column.
        /// </summary>
        public static string Automation_SelectAllColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_SelectAllColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selects or deselects all services in the list..
        /// </summary>
        public static string Automation_SelectAllServicesCheckBox_HelpText {
            get {
                return ResourceManager.GetString("Automation_SelectAllServicesCheckBox_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Services.
        /// </summary>
        public static string Automation_SelectAllServicesCheckBox_Name {
            get {
                return ResourceManager.GetString("Automation_SelectAllServicesCheckBox_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select this service for bulk actions..
        /// </summary>
        public static string Automation_SelectServiceCheckBox_HelpText {
            get {
                return ResourceManager.GetString("Automation_SelectServiceCheckBox_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Service.
        /// </summary>
        public static string Automation_SelectServiceCheckBox_Name {
            get {
                return ResourceManager.GetString("Automation_SelectServiceCheckBox_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displays a searchable list of managed services. Use the search field to filter by service name..
        /// </summary>
        public static string Automation_ServiceListControl_HelpText {
            get {
                return ResourceManager.GetString("Automation_ServiceListControl_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service List Control.
        /// </summary>
        public static string Automation_ServiceListControl_Name {
            get {
                return ResourceManager.GetString("Automation_ServiceListControl_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Name Header.
        /// </summary>
        public static string Automation_ServiceNameHeader_Name {
            get {
                return ResourceManager.GetString("Automation_ServiceNameHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List of managed services..
        /// </summary>
        public static string Automation_ServicesDataGrid_HelpText {
            get {
                return ResourceManager.GetString("Automation_ServicesDataGrid_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services List.
        /// </summary>
        public static string Automation_ServicesDataGrid_Name {
            get {
                return ResourceManager.GetString("Automation_ServicesDataGrid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a keyword to search services..
        /// </summary>
        public static string Automation_SidebarSearchTextBox_HelpText {
            get {
                return ResourceManager.GetString("Automation_SidebarSearchTextBox_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Services.
        /// </summary>
        public static string Automation_SidebarSearchTextBox_Name {
            get {
                return ResourceManager.GetString("Automation_SidebarSearchTextBox_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services List.
        /// </summary>
        public static string Automation_SidebarServicesDataGrid_Name {
            get {
                return ResourceManager.GetString("Automation_SidebarServicesDataGrid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts all selected services..
        /// </summary>
        public static string Automation_StartSelectedButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_StartSelectedButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the current service..
        /// </summary>
        public static string Automation_StartServiceButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_StartServiceButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Service.
        /// </summary>
        public static string Automation_StartServiceButton_Name {
            get {
                return ResourceManager.GetString("Automation_StartServiceButton_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configured startup type for the service..
        /// </summary>
        public static string Automation_StartupTypeColumnCell_HelpText {
            get {
                return ResourceManager.GetString("Automation_StartupTypeColumnCell_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Type Column.
        /// </summary>
        public static string Automation_StartupTypeColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_StartupTypeColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current status of the service..
        /// </summary>
        public static string Automation_StatusColumnCell_HelpText {
            get {
                return ResourceManager.GetString("Automation_StatusColumnCell_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Column.
        /// </summary>
        public static string Automation_StatusColumnHeader_Name {
            get {
                return ResourceManager.GetString("Automation_StatusColumnHeader_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops all selected services..
        /// </summary>
        public static string Automation_StopSelectedButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_StopSelectedButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stops the current service..
        /// </summary>
        public static string Automation_StopServiceButton_HelpText {
            get {
                return ResourceManager.GetString("Automation_StopServiceButton_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Service.
        /// </summary>
        public static string Automation_StopServiceButton_Name {
            get {
                return ResourceManager.GetString("Automation_StopServiceButton_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        public static string Button_CollapseAll {
            get {
                return ResourceManager.GetString("Button_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Configuration.
        /// </summary>
        public static string Button_Config {
            get {
                return ResourceManager.GetString("Button_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy PID.
        /// </summary>
        public static string Button_CopyPid {
            get {
                return ResourceManager.GetString("Button_CopyPid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        public static string Button_ExpandAll {
            get {
                return ResourceManager.GetString("Button_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export JSON.
        /// </summary>
        public static string Button_ExportJSON {
            get {
                return ResourceManager.GetString("Button_ExportJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export XML.
        /// </summary>
        public static string Button_ExportXML {
            get {
                return ResourceManager.GetString("Button_ExportXML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Button_Install {
            get {
                return ResourceManager.GetString("Button_Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Actions.
        /// </summary>
        public static string Button_More {
            get {
                return ResourceManager.GetString("Button_More", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Button_Refresh {
            get {
                return ResourceManager.GetString("Button_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Button_Remove {
            get {
                return ResourceManager.GetString("Button_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart.
        /// </summary>
        public static string Button_Restart {
            get {
                return ResourceManager.GetString("Button_Restart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Selected.
        /// </summary>
        public static string Button_RestartSelected {
            get {
                return ResourceManager.GetString("Button_RestartSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ▶ Resume.
        /// </summary>
        public static string Button_Resume {
            get {
                return ResourceManager.GetString("Button_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Button_Search {
            get {
                return ResourceManager.GetString("Button_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string Button_Searching {
            get {
                return ResourceManager.GetString("Button_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Button_Start {
            get {
                return ResourceManager.GetString("Button_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Selected.
        /// </summary>
        public static string Button_StartSelected {
            get {
                return ResourceManager.GetString("Button_StartSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Button_Stop {
            get {
                return ResourceManager.GetString("Button_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Selected.
        /// </summary>
        public static string Button_StopSelected {
            get {
                return ResourceManager.GetString("Button_StopSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Button_Uninstall {
            get {
                return ResourceManager.GetString("Button_Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string Column_CPU {
            get {
                return ResourceManager.GetString("Column_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Column_Description {
            get {
                return ResourceManager.GetString("Column_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Column_Level {
            get {
                return ResourceManager.GetString("Column_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log On As.
        /// </summary>
        public static string Column_LogOnAs {
            get {
                return ResourceManager.GetString("Column_LogOnAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message.
        /// </summary>
        public static string Column_Message {
            get {
                return ResourceManager.GetString("Column_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Column_Name {
            get {
                return ResourceManager.GetString("Column_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string Column_Pid {
            get {
                return ResourceManager.GetString("Column_Pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string Column_RAM {
            get {
                return ResourceManager.GetString("Column_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        public static string Column_Service {
            get {
                return ResourceManager.GetString("Column_Service", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup Type.
        /// </summary>
        public static string Column_StartupType {
            get {
                return ResourceManager.GetString("Column_StartupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Column_Status {
            get {
                return ResourceManager.GetString("Column_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string Column_Time {
            get {
                return ResourceManager.GetString("Column_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart selected services?.
        /// </summary>
        public static string Confirm_RestartSelectedServices {
            get {
                return ResourceManager.GetString("Confirm_RestartSelectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start selected services?.
        /// </summary>
        public static string Confirm_StartSelectedServices {
            get {
                return ResourceManager.GetString("Confirm_StartSelectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop selected services?.
        /// </summary>
        public static string Confirm_StopSelectedServices {
            get {
                return ResourceManager.GetString("Confirm_StopSelectedServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable service stdout/stderr redirection to live-monitor console output.
        /// </summary>
        public static string Console_Info {
            get {
                return ResourceManager.GetString("Console_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service dependency tree (via SCM).
        /// </summary>
        public static string Dependencies_Info {
            get {
                return ResourceManager.GetString("Dependencies_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Configuration exported successfully..
        /// </summary>
        public static string ExportJson_Success {
            get {
                return ResourceManager.GetString("ExportJson_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Configuration exported successfully..
        /// </summary>
        public static string ExportXml_Success {
            get {
                return ResourceManager.GetString("ExportXml_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found {0} logs in {1}.
        /// </summary>
        public static string Footer_Log_Many {
            get {
                return ResourceManager.GetString("Footer_Log_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No logs found in {1}.
        /// </summary>
        public static string Footer_Log_None {
            get {
                return ResourceManager.GetString("Footer_Log_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found 1 log in {1}.
        /// </summary>
        public static string Footer_Log_One {
            get {
                return ResourceManager.GetString("Footer_Log_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded {0} services in {1}.
        /// </summary>
        public static string Footer_Service_Many {
            get {
                return ResourceManager.GetString("Footer_Service_Many", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services loaded in {1}.
        /// </summary>
        public static string Footer_Service_None {
            get {
                return ResourceManager.GetString("Footer_Service_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded 1 service in {1}.
        /// </summary>
        public static string Footer_Service_One {
            get {
                return ResourceManager.GetString("Footer_Service_One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import JSON Configuration..
        /// </summary>
        public static string ImportJson_Error {
            get {
                return ResourceManager.GetString("ImportJson_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Configuration imported successfully..
        /// </summary>
        public static string ImportJson_Success {
            get {
                return ResourceManager.GetString("ImportJson_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import XML Configuration..
        /// </summary>
        public static string ImportXml_Error {
            get {
                return ResourceManager.GetString("ImportXml_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML Configuration imported successfully..
        /// </summary>
        public static string ImportXml_Success {
            get {
                return ResourceManager.GetString("ImportXml_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 🔍 Filter:.
        /// </summary>
        public static string Label_ConsoleFilter {
            get {
                return ResourceManager.GetString("Label_ConsoleFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Console.
        /// </summary>
        public static string Label_ConsoleTab {
            get {
                return ResourceManager.GetString("Label_ConsoleTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string Label_Copy {
            get {
                return ResourceManager.GetString("Label_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU.
        /// </summary>
        public static string Label_CPU {
            get {
                return ResourceManager.GetString("Label_CPU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status: Running (green), Stopped (red), Cycle (orange).
        /// </summary>
        public static string Label_Dependencies_Gear_Info {
            get {
                return ResourceManager.GetString("Label_Dependencies_Gear_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependencies.
        /// </summary>
        public static string Label_DependenciesTab {
            get {
                return ResourceManager.GetString("Label_DependenciesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service statuses auto-refresh - Press F5 to refresh the full list.
        /// </summary>
        public static string Label_F5_Shortcut {
            get {
                return ResourceManager.GetString("Label_F5_Shortcut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F5 to refresh the dependency tree.
        /// </summary>
        public static string Label_F5_Shortcut_Dependencies {
            get {
                return ResourceManager.GetString("Label_F5_Shortcut_Dependencies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press F5 to refresh logs.
        /// </summary>
        public static string Label_F5_Shortcut_Logs {
            get {
                return ResourceManager.GetString("Label_F5_Shortcut_Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fetching....
        /// </summary>
        public static string Label_Fetching {
            get {
                return ResourceManager.GetString("Label_Fetching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From:.
        /// </summary>
        public static string Label_From {
            get {
                return ResourceManager.GetString("Label_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keyword:.
        /// </summary>
        public static string Label_Keyword {
            get {
                return ResourceManager.GetString("Label_Keyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level:.
        /// </summary>
        public static string Label_Level {
            get {
                return ResourceManager.GetString("Label_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logs.
        /// </summary>
        public static string Label_LogsTab {
            get {
                return ResourceManager.GetString("Label_LogsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        public static string Label_PerformanceTab {
            get {
                return ResourceManager.GetString("Label_PerformanceTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID.
        /// </summary>
        public static string Label_Pid {
            get {
                return ResourceManager.GetString("Label_Pid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RAM.
        /// </summary>
        public static string Label_RAM {
            get {
                return ResourceManager.GetString("Label_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        public static string Label_ServicesTab {
            get {
                return ResourceManager.GetString("Label_ServicesTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To:.
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Servy Manager.
        /// </summary>
        public static string Menu_About {
            get {
                return ResourceManager.GetString("Menu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for updates....
        /// </summary>
        public static string Menu_CheckUpdates {
            get {
                return ResourceManager.GetString("Menu_CheckUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurator.
        /// </summary>
        public static string Menu_Config {
            get {
                return ResourceManager.GetString("Menu_Config", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help / Documentation.
        /// </summary>
        public static string Menu_Doc {
            get {
                return ResourceManager.GetString("Menu_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Menu_Help {
            get {
                return ResourceManager.GetString("Menu_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string Menu_Import {
            get {
                return ResourceManager.GetString("Menu_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import JSON configuration.
        /// </summary>
        public static string Menu_ImportJson {
            get {
                return ResourceManager.GetString("Menu_ImportJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import XML configuration.
        /// </summary>
        public static string Menu_ImportXml {
            get {
                return ResourceManager.GetString("Menu_ImportXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All operations failed..
        /// </summary>
        public static string Msg_AllOperationsFailed {
            get {
                return ResourceManager.GetString("Msg_AllOperationsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy content to the clipboard. The clipboard may be in use by another application..
        /// </summary>
        public static string Msg_ClipboardCopyFailed {
            get {
                return ResourceManager.GetString("Msg_ClipboardCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to launch the Desktop application..
        /// </summary>
        public static string Msg_DesktopAppLaunchFailed {
            get {
                return ResourceManager.GetString("Msg_DesktopAppLaunchFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servy Desktop App not found..
        /// </summary>
        public static string Msg_DesktopAppNotFound {
            get {
                return ResourceManager.GetString("Msg_DesktopAppNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load service dependency tree..
        /// </summary>
        public static string Msg_FailedToLoadDependencyTree {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadDependencyTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load JSON service configuration..
        /// </summary>
        public static string Msg_FailedToLoadJson {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to load XML service configuration..
        /// </summary>
        public static string Msg_FailedToLoadXml {
            get {
                return ResourceManager.GetString("Msg_FailedToLoadXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service with this name already exists. Would you like to replace it?
        ///
        ///You need to click Install after importing and restart the service for changes to take effect.
        ///If the service is disabled and marked for deletion, installation will fail until you restart your PC..
        /// </summary>
        public static string Msg_ImportServiceConfirmation {
            get {
                return ResourceManager.GetString("Msg_ImportServiceConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service wrapper executable not found..
        /// </summary>
        public static string Msg_InvalidWrapperExePath {
            get {
                return ResourceManager.GetString("Msg_InvalidWrapperExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while switching tabs. Please try again..
        /// </summary>
        public static string Msg_MainTabControl_SelectionChangedError {
            get {
                return ResourceManager.GetString("Msg_MainTabControl_SelectionChangedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No services selected..
        /// </summary>
        public static string Msg_NoServicesSelected {
            get {
                return ResourceManager.GetString("Msg_NoServicesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation completed successfully..
        /// </summary>
        public static string Msg_OperationCompletedSuccessfully {
            get {
                return ResourceManager.GetString("Msg_OperationCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while performing the operation on: {0}.
        /// </summary>
        public static string Msg_OperationCompletedWithErrorsDetails {
            get {
                return ResourceManager.GetString("Msg_OperationCompletedWithErrorsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PID copied to clipboard..
        /// </summary>
        public static string Msg_PidCopied {
            get {
                return ResourceManager.GetString("Msg_PidCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy PID to clipboard..
        /// </summary>
        public static string Msg_PidCopyFailed {
            get {
                return ResourceManager.GetString("Msg_PidCopyFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove this service? All service configuration will be permanently lost and cannot be recovered..
        /// </summary>
        public static string Msg_RemoveServiceConfirm {
            get {
                return ResourceManager.GetString("Msg_RemoveServiceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servy Manager requires administrative privileges to manage system services..
        /// </summary>
        public static string Msg_SecurityWarningMessage {
            get {
                return ResourceManager.GetString("Msg_SecurityWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elevation Required.
        /// </summary>
        public static string Msg_SecurityWarningTitle {
            get {
                return ResourceManager.GetString("Msg_SecurityWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A service with this name already exists. Would you like to replace it?
        ///
        ///If the service is disabled and marked for deletion, the installation will fail until you restart your PC..
        /// </summary>
        public static string Msg_ServiceAlreadyExists {
            get {
                return ResourceManager.GetString("Msg_ServiceAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified service is disabled..
        /// </summary>
        public static string Msg_ServiceDisabledError {
            get {
                return ResourceManager.GetString("Msg_ServiceDisabledError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was installed successfully..
        /// </summary>
        public static string Msg_ServiceInstalled {
            get {
                return ResourceManager.GetString("Msg_ServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was restarted successfully..
        /// </summary>
        public static string Msg_ServiceRestarted {
            get {
                return ResourceManager.GetString("Msg_ServiceRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was started successfully..
        /// </summary>
        public static string Msg_ServiceStarted {
            get {
                return ResourceManager.GetString("Msg_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was stopped successfully..
        /// </summary>
        public static string Msg_ServiceStopped {
            get {
                return ResourceManager.GetString("Msg_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Security Risk: Your system is using an outdated SQLite engine ({0}). This version of the application requires SQLite {1} or higher to mitigate CVE-2025-6965..
        /// </summary>
        public static string Msg_SqliteVersionWarningMessage {
            get {
                return ResourceManager.GetString("Msg_SqliteVersionWarningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert.
        /// </summary>
        public static string Msg_SqliteVersionWarningTitle {
            get {
                return ResourceManager.GetString("Msg_SqliteVersionWarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string Msg_UnexpectedError {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall this service? All service configuration will be permanently lost and cannot be recovered..
        /// </summary>
        public static string Msg_UninstallServiceConfirm {
            get {
                return ResourceManager.GetString("Msg_UninstallServiceConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export JSON configuration.
        /// </summary>
        public static string SaveFileDialog_JsonTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_JsonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export XML configuration.
        /// </summary>
        public static string SaveFileDialog_XmlTitle {
            get {
                return ResourceManager.GetString("SaveFileDialog_XmlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Servy Manager....
        /// </summary>
        public static string Splash_Text {
            get {
                return ResourceManager.GetString("Splash_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic.
        /// </summary>
        public static string StartupType_Automatic {
            get {
                return ResourceManager.GetString("StartupType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatic (delayed).
        /// </summary>
        public static string StartupType_AutomaticDelayedStart {
            get {
                return ResourceManager.GetString("StartupType_AutomaticDelayedStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string StartupType_Disabled {
            get {
                return ResourceManager.GetString("StartupType_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string StartupType_Manual {
            get {
                return ResourceManager.GetString("StartupType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string StartupType_Unknown {
            get {
                return ResourceManager.GetString("StartupType_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue Pending.
        /// </summary>
        public static string Status_ContinuePending {
            get {
                return ResourceManager.GetString("Status_ContinuePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string Status_NotInstalled {
            get {
                return ResourceManager.GetString("Status_NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paused.
        /// </summary>
        public static string Status_Paused {
            get {
                return ResourceManager.GetString("Status_Paused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause Pending.
        /// </summary>
        public static string Status_PausePending {
            get {
                return ResourceManager.GetString("Status_PausePending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Running.
        /// </summary>
        public static string Status_Running {
            get {
                return ResourceManager.GetString("Status_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Pending.
        /// </summary>
        public static string Status_StartPending {
            get {
                return ResourceManager.GetString("Status_StartPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopped.
        /// </summary>
        public static string Status_Stopped {
            get {
                return ResourceManager.GetString("Status_Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop Pending.
        /// </summary>
        public static string Status_StopPending {
            get {
                return ResourceManager.GetString("Status_StopPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string Status_Unknown {
            get {
                return ResourceManager.GetString("Status_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Servy Manager {0}
        ///
        ///Servy Manager provides a clean and simple interface for managing Windows services created with Servy. Start, stop, configure, and monitor services with ease.
        ///
        ///Built with {1}
        ///
        ///Licensed under the MIT License.
        ///
        ///Copyright © {2} Akram El Assas. All rights reserved..
        /// </summary>
        public static string Text_About {
            get {
                return ResourceManager.GetString("Text_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse all nodes in the dependency tree.
        /// </summary>
        public static string Tooltip_CollapseAll {
            get {
                return ResourceManager.GetString("Tooltip_CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circular dependency detected.
        /// </summary>
        public static string Tooltip_Cycle {
            get {
                return ResourceManager.GetString("Tooltip_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This dependency is unavailable or inaccessible..
        /// </summary>
        public static string Tooltip_DependencyUnavailable {
            get {
                return ResourceManager.GetString("Tooltip_DependencyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand all nodes in the dependency tree.
        /// </summary>
        public static string Tooltip_ExpandAll {
            get {
                return ResourceManager.GetString("Tooltip_ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh the service dependency tree.
        /// </summary>
        public static string Tooltip_Refresh {
            get {
                return ResourceManager.GetString("Tooltip_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume live updates.
        /// </summary>
        public static string Tooltip_Resume {
            get {
                return ResourceManager.GetString("Tooltip_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is running.
        /// </summary>
        public static string Tooltip_ServiceRunning {
            get {
                return ResourceManager.GetString("Tooltip_ServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This service is stopped.
        /// </summary>
        public static string Tooltip_ServiceStopped {
            get {
                return ResourceManager.GetString("Tooltip_ServiceStopped", resourceCulture);
            }
        }
    }
}
