<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <RuntimeIdentifiers>win-x64;win-arm64</RuntimeIdentifiers>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>

    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>false</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <IncludeAllContentForSelfExtract>false</IncludeAllContentForSelfExtract>
    <InvariantGlobalization>false</InvariantGlobalization>

    <ApplicationIcon>servy.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>

    <PublishReadyToRun>false</PublishReadyToRun>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy</AssemblyTitle>
    <Description>A tool to run any app as a Windows Service</Description>
    <Product>Servy</Product>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\handle64.exe" />
    <None Remove="Resources\handle64a.exe" />
    <None Remove="Resources\Servy.Service.exe" />
    <None Remove="Resources\Servy.Service.pdb" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.desktop.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="servy.ico" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\handle64.exe" />
    <EmbeddedResource Include="Resources\handle64a.exe" />
    <EmbeddedResource Include="Resources\Servy.Service.exe" />
    <EmbeddedResource Include="Resources\Servy.Service.pdb" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\Strings.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Resources\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Servy.Core\Servy.Core.csproj" />
    <ProjectReference Include="..\Servy.Infrastructure\Servy.Infrastructure.csproj" />
    <ProjectReference Include="..\Servy.UI\Servy.UI.csproj" />
  </ItemGroup>

</Project>
