<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.Infrastructure.UnitTests</AssemblyTitle>
    <Description>Servy.Infrastructure unit tests</Description>
    <Product>Servy.Infrastructure.UnitTests</Product>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Moq" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Servy.Core\Servy.Core.csproj" />
    <ProjectReference Include="..\..\src\Servy.Infrastructure\Servy.Infrastructure.csproj" />
    <ProjectReference Include="..\Servy.Testing\Servy.Testing.csproj" />
  </ItemGroup>

</Project>
