//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servy.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Servy.Core.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_AllFiles {
            get {
                return ResourceManager.GetString("FileFilter_AllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files (*.exe)|*.exe|All files (*.*)|*.*.
        /// </summary>
        public static string FileFilter_Executable {
            get {
                return ResourceManager.GetString("FileFilter_Executable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON files (*.json)|*.json.
        /// </summary>
        public static string FileFilter_Json {
            get {
                return ResourceManager.GetString("FileFilter_Json", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML files (*.xml)|*.xml.
        /// </summary>
        public static string FileFilter_Xml {
            get {
                return ResourceManager.GetString("FileFilter_Xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator privileges are required..
        /// </summary>
        public static string Msg_AdminRightsRequired {
            get {
                return ResourceManager.GetString("Msg_AdminRightsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arguments for field &apos;{0}&apos; exceed the Windows command-line limit of {1} characters..
        /// </summary>
        public static string Msg_ArgumentsLengthReachedForField {
            get {
                return ResourceManager.GetString("Msg_ArgumentsLengthReachedForField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration file &apos;{0}&apos; exceeds maximum size ({1} MB)..
        /// </summary>
        public static string Msg_ConfigSizeLimitReached {
            get {
                return ResourceManager.GetString("Msg_ConfigSizeLimitReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU affinity core index &apos;{0}&apos; is out of bounds (0-{1})..
        /// </summary>
        public static string Msg_CoreIndexOutOfBounds {
            get {
                return ResourceManager.GetString("Msg_CoreIndexOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU affinity core index in range &apos;{0}&apos; is out of bounds (0-{1})..
        /// </summary>
        public static string Msg_CoreIndexRangeOutOfBounds {
            get {
                return ResourceManager.GetString("Msg_CoreIndexRangeOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency &apos;{0}&apos; is not accessible (Access Denied)..
        /// </summary>
        public static string Msg_DependencyAccessDenied {
            get {
                return ResourceManager.GetString("Msg_DependencyAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dependency &apos;{0}&apos; is unavailable..
        /// </summary>
        public static string Msg_DependencyUnavailable {
            get {
                return ResourceManager.GetString("Msg_DependencyUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description exceeds {0} characters..
        /// </summary>
        public static string Msg_DescriptionLengthReached {
            get {
                return ResourceManager.GetString("Msg_DescriptionLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (details unavailable: access denied).
        /// </summary>
        public static string Msg_DetailsUnavailableAccessDenied {
            get {
                return ResourceManager.GetString("Msg_DetailsUnavailableAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display name exceeds {0} characters..
        /// </summary>
        public static string Msg_DisplayNameLengthReached {
            get {
                return ResourceManager.GetString("Msg_DisplayNameLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU affinity mask &apos;{0}&apos; selects no processors..
        /// </summary>
        public static string Msg_EmptyAffinityMask {
            get {
                return ResourceManager.GetString("Msg_EmptyAffinityMask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variable &apos;{0}&apos; contains a forbidden newline character. Multi-line values are not supported..
        /// </summary>
        public static string Msg_EnvironmentVariableForbiddenNewline {
            get {
                return ResourceManager.GetString("Msg_EnvironmentVariableForbiddenNewline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Environment variable key cannot be empty..
        /// </summary>
        public static string Msg_EnvironmentVariableKeyEmpty {
            get {
                return ResourceManager.GetString("Msg_EnvironmentVariableKeyEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The environment variable key &apos;{0}&apos; contains illegal characters..
        /// </summary>
        public static string Msg_EnvironmentVariableKeyInvalidChars {
            get {
                return ResourceManager.GetString("Msg_EnvironmentVariableKeyInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each environment variable must contain an unescaped &apos;=&apos; character to separate the key from the value..
        /// </summary>
        public static string Msg_EnvironmentVariableMissingEquals {
            get {
                return ResourceManager.GetString("Msg_EnvironmentVariableMissingEquals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value of environment variable &apos;{0}&apos; contains illegal characters..
        /// </summary>
        public static string Msg_EnvironmentVariableValueInvalidChars {
            get {
                return ResourceManager.GetString("Msg_EnvironmentVariableValueInvalidChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access denied to Windows Event Log. Please ensure the application is running with sufficient privileges (Administrator)..
        /// </summary>
        public static string Msg_EventLogAccessDenied {
            get {
                return ResourceManager.GetString("Msg_EventLogAccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access Windows Event Log. Ensure the &apos;Windows Event Log&apos; service is running and the query is valid..
        /// </summary>
        public static string Msg_EventLogUnavailable {
            get {
                return ResourceManager.GetString("Msg_EventLogUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service process path cannot be empty..
        /// </summary>
        public static string Msg_ExecutablePathRequired {
            get {
                return ResourceManager.GetString("Msg_ExecutablePathRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A fatal error occurred and the application must close. Detailed diagnostics have been saved to the log file..
        /// </summary>
        public static string Msg_FatalError_Body {
            get {
                return ResourceManager.GetString("Msg_FatalError_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servy - Fatal Error.
        /// </summary>
        public static string Msg_FatalError_Title {
            get {
                return ResourceManager.GetString("Msg_FatalError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPU affinity mask &apos;{0}&apos; selects processors outside the allowable range (0-{1})..
        /// </summary>
        public static string Msg_HexMaskOutOfBounds {
            get {
                return ResourceManager.GetString("Msg_HexMaskOutOfBounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} deserialization resulted in an empty service definition..
        /// </summary>
        public static string Msg_ImportEmptyDefinition {
            get {
                return ResourceManager.GetString("Msg_ImportEmptyDefinition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found: {0}.
        /// </summary>
        public static string Msg_ImportFileNotFound {
            get {
                return ResourceManager.GetString("Msg_ImportFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} input cannot be empty or whitespace..
        /// </summary>
        public static string Msg_ImportInputEmptyOrWhitespace {
            get {
                return ResourceManager.GetString("Msg_ImportInputEmptyOrWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} structure: {1}..
        /// </summary>
        public static string Msg_ImportInvalidStructure {
            get {
                return ResourceManager.GetString("Msg_ImportInvalidStructure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize service configuration from JSON content..
        /// </summary>
        public static string Msg_ImportJsonDeserializationFailed {
            get {
                return ResourceManager.GetString("Msg_ImportJsonDeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import service from JSON: {0}.
        /// </summary>
        public static string Msg_ImportJsonFailed {
            get {
                return ResourceManager.GetString("Msg_ImportJsonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON content cannot be null or empty..
        /// </summary>
        public static string Msg_ImportJsonNullOrEmpty {
            get {
                return ResourceManager.GetString("Msg_ImportJsonNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} payload exceeds the maximum allowed size of {1} MB..
        /// </summary>
        public static string Msg_ImportPayloadTooLarge {
            get {
                return ResourceManager.GetString("Msg_ImportPayloadTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} structure error: {1}..
        /// </summary>
        public static string Msg_ImportStructureError {
            get {
                return ResourceManager.GetString("Msg_ImportStructureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to deserialize service configuration from XML content..
        /// </summary>
        public static string Msg_ImportXmlDeserializationFailed {
            get {
                return ResourceManager.GetString("Msg_ImportXmlDeserializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to import service from XML: {0}.
        /// </summary>
        public static string Msg_ImportXmlFailed {
            get {
                return ResourceManager.GetString("Msg_ImportXmlFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to XML content cannot be null or empty..
        /// </summary>
        public static string Msg_ImportXmlNullOrEmpty {
            get {
                return ResourceManager.GetString("Msg_ImportXmlNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} in configuration..
        /// </summary>
        public static string Msg_InvalidConfig {
            get {
                return ResourceManager.GetString("Msg_InvalidConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CPU affinity core specification: &apos;{0}&apos;..
        /// </summary>
        public static string Msg_InvalidCoreSpecification {
            get {
                return ResourceManager.GetString("Msg_InvalidCoreSpecification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The failure program path is invalid..
        /// </summary>
        public static string Msg_InvalidFailureProgramPath {
            get {
                return ResourceManager.GetString("Msg_InvalidFailureProgramPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified failure program startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidFailureProgramStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidFailureProgramStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat interval must be a number of seconds between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidHeartbeatInterval {
            get {
                return ResourceManager.GetString("Msg_InvalidHeartbeatInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The provided heartbeat monitoring URL must be a well-formed absolute HTTP or HTTPS URL..
        /// </summary>
        public static string Msg_InvalidHeartbeatUrl {
            get {
                return ResourceManager.GetString("Msg_InvalidHeartbeatUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heartbeat URL timeout must be a number of seconds between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidHeartbeatUrlTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidHeartbeatUrlTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid CPU affinity hexadecimal format: &apos;{0}&apos;..
        /// </summary>
        public static string Msg_InvalidHexAffinityFormat {
            get {
                return ResourceManager.GetString("Msg_InvalidHexAffinityFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max failed checks must be a number between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidMaxFailedChecks {
            get {
                return ResourceManager.GetString("Msg_InvalidMaxFailedChecks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max restart attempts must be a number between {0} and {1}. Set to 0 for unlimited restart attempts..
        /// </summary>
        public static string Msg_InvalidMaxRestartAttempts {
            get {
                return ResourceManager.GetString("Msg_InvalidMaxRestartAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max rotations must be a number between {0} and {1}. Set to 0 for unlimited rotations..
        /// </summary>
        public static string Msg_InvalidMaxRotations {
            get {
                return ResourceManager.GetString("Msg_InvalidMaxRotations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified path is invalid..
        /// </summary>
        public static string Msg_InvalidPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid {0} in configuration. Ensure the path exists and is accessible..
        /// </summary>
        public static string Msg_InvalidPathInConfig {
            get {
                return ResourceManager.GetString("Msg_InvalidPathInConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post-launch process path is invalid..
        /// </summary>
        public static string Msg_InvalidPostLaunchPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPostLaunchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified post-launch startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidPostLaunchStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidPostLaunchStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The post-stop process path is invalid..
        /// </summary>
        public static string Msg_InvalidPostStopPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPostStopPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified post-stop startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidPostStopStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidPostStopStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pre-launch process path is invalid..
        /// </summary>
        public static string Msg_InvalidPreLaunchPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-launch retry attempts must be a number between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidPreLaunchRetryAttempts {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchRetryAttempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified pre-launch startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidPreLaunchStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified pre-launch stderr file path is invalid..
        /// </summary>
        public static string Msg_InvalidPreLaunchStderrPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchStderrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified pre-launch stdout file path is invalid..
        /// </summary>
        public static string Msg_InvalidPreLaunchStdoutPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchStdoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-launch timeout must be a number of seconds between {0} and {1}. Set the timeout to 0 to run the pre-launch hook in fire-and-forget mode. When set to 0, the hook is started and the service is launched immediately without waiting for completion. Use fire-and-forget only for tasks that do not affect the service&apos;s ability to start or run correctly. Stdout/Stderr redirection and retries are not available in fire-and-forget mode..
        /// </summary>
        public static string Msg_InvalidPreLaunchTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidPreLaunchTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The pre-stop process path is invalid..
        /// </summary>
        public static string Msg_InvalidPreStopPath {
            get {
                return ResourceManager.GetString("Msg_InvalidPreStopPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified pre-stop startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidPreStopStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidPreStopStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pre-stop timeout must be a number of seconds between {0} and {1}. Set the timeout to 0 to run the pre-stop process in fire-and-forget mode..
        /// </summary>
        public static string Msg_InvalidPreStopTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidPreStopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation size must be a number of megabytes (MB) between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidRotationSize {
            get {
                return ResourceManager.GetString("Msg_InvalidRotationSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid service name &apos;{0}&apos;. Only letters, digits, hyphens, underscores, periods, spaces, and dollar signs ($) are allowed, optionally preceded by &apos;+&apos; to reference a load-order group..
        /// </summary>
        public static string Msg_InvalidServiceDependencyName {
            get {
                return ResourceManager.GetString("Msg_InvalidServiceDependencyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name contains invalid characters. Avoid using &apos;\&apos;, &apos;/&apos;, &apos;:&apos;, &apos;*&apos;, &apos;?&apos;, &apos;&quot;&apos;, &apos;&lt;&apos;, &apos;&gt;&apos;, &apos;|&apos;, and non-printable characters..
        /// </summary>
        public static string Msg_InvalidServiceName {
            get {
                return ResourceManager.GetString("Msg_InvalidServiceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start timeout must be a number of seconds between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidStartTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidStartTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified startup directory is invalid..
        /// </summary>
        public static string Msg_InvalidStartupDirectory {
            get {
                return ResourceManager.GetString("Msg_InvalidStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified stderr file path is invalid..
        /// </summary>
        public static string Msg_InvalidStderrPath {
            get {
                return ResourceManager.GetString("Msg_InvalidStderrPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified stdout file path is invalid..
        /// </summary>
        public static string Msg_InvalidStdoutPath {
            get {
                return ResourceManager.GetString("Msg_InvalidStdoutPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop timeout must be a number of seconds between {0} and {1}..
        /// </summary>
        public static string Msg_InvalidStopTimeout {
            get {
                return ResourceManager.GetString("Msg_InvalidStopTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service wrapper executable not found..
        /// </summary>
        public static string Msg_InvalidWrapperExePath {
            get {
                return ResourceManager.GetString("Msg_InvalidWrapperExePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inverted CPU affinity core range &apos;{0}&apos;: the start index is greater than the end index..
        /// </summary>
        public static string Msg_InvertedCoreRange {
            get {
                return ResourceManager.GetString("Msg_InvertedCoreRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match..
        /// </summary>
        public static string Msg_PasswordsDontMatch {
            get {
                return ResourceManager.GetString("Msg_PasswordsDontMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Exporting configurations to directory junctions or symlinks is prohibited to prevent path redirection attacks..
        /// </summary>
        public static string Msg_SecurityDirReparsePointExportProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityDirReparsePointExportProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Importing configurations through directory junctions or symlinks is prohibited to prevent path redirection attacks..
        /// </summary>
        public static string Msg_SecurityDirReparsePointProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityDirReparsePointProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Exporting configurations to file symbolic links or junctions is prohibited to prevent path redirection attacks..
        /// </summary>
        public static string Msg_SecurityFileReparsePointExportProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityFileReparsePointExportProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Importing configurations through file symbolic links or junctions is prohibited to prevent path redirection attacks..
        /// </summary>
        public static string Msg_SecurityFileReparsePointProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityFileReparsePointProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Could not obtain a file handle for the target..
        /// </summary>
        public static string Msg_SecurityHandleInvalid {
            get {
                return ResourceManager.GetString("Msg_SecurityHandleInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Path validation failed in the kernel probe (path serialization)..
        /// </summary>
        public static string Msg_SecurityHandleSerializationFailed {
            get {
                return ResourceManager.GetString("Msg_SecurityHandleSerializationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Path validation failed in the kernel probe (size allocation)..
        /// </summary>
        public static string Msg_SecurityHandleSizeProbeFailed {
            get {
                return ResourceManager.GetString("Msg_SecurityHandleSizeProbeFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Target file handle validation was rejected ({0})..
        /// </summary>
        public static string Msg_SecurityHandleValidationFailed {
            get {
                return ResourceManager.GetString("Msg_SecurityHandleValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Invalid file type &apos;{0}&apos;. Only .json and .xml files are supported..
        /// </summary>
        public static string Msg_SecurityInvalidFileType {
            get {
                return ResourceManager.GetString("Msg_SecurityInvalidFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Exporting to network drives (including mapped UNC shares) is prohibited..
        /// </summary>
        public static string Msg_SecurityNetworkDriveExportProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityNetworkDriveExportProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Importing from network drives (including mapped UNC shares) is prohibited..
        /// </summary>
        public static string Msg_SecurityNetworkDriveProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityNetworkDriveProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: The resolved path targets protected system directory &apos;{0}&apos;. Import prohibited..
        /// </summary>
        public static string Msg_SecurityProtectedDirectory {
            get {
                return ResourceManager.GetString("Msg_SecurityProtectedDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: The resolved path targets protected system directory &apos;{0}&apos;. Export prohibited..
        /// </summary>
        public static string Msg_SecurityProtectedDirectoryExport {
            get {
                return ResourceManager.GetString("Msg_SecurityProtectedDirectoryExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: &apos;{0}&apos; is a reserved Windows device name and cannot be used..
        /// </summary>
        public static string Msg_SecurityReservedDeviceName {
            get {
                return ResourceManager.GetString("Msg_SecurityReservedDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Resolved file target points directly to a UNC destination. Import aborted..
        /// </summary>
        public static string Msg_SecurityResolvedUncDestination {
            get {
                return ResourceManager.GetString("Msg_SecurityResolvedUncDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Resolved file target points directly to a UNC destination. Export aborted..
        /// </summary>
        public static string Msg_SecurityResolvedUncDestinationExport {
            get {
                return ResourceManager.GetString("Msg_SecurityResolvedUncDestinationExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Exporting to UNC paths is prohibited to prevent configuration exfiltration..
        /// </summary>
        public static string Msg_SecurityUncPathExportProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityUncPathExportProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Alert: Importing from UNC paths is prohibited to prevent malicious configuration injection..
        /// </summary>
        public static string Msg_SecurityUncPathProhibited {
            get {
                return ResourceManager.GetString("Msg_SecurityUncPathProhibited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service dependency &apos;{0}&apos; exceeds the maximum length of {1} characters..
        /// </summary>
        public static string Msg_ServiceDependencyNameLengthReachedForName {
            get {
                return ResourceManager.GetString("Msg_ServiceDependencyNameLengthReachedForName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was installed successfully..
        /// </summary>
        public static string Msg_ServiceInstalled {
            get {
                return ResourceManager.GetString("Msg_ServiceInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name cannot have leading whitespace..
        /// </summary>
        public static string Msg_ServiceNameContainsLeadingWhitespace {
            get {
                return ResourceManager.GetString("Msg_ServiceNameContainsLeadingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name cannot have trailing whitespace..
        /// </summary>
        public static string Msg_ServiceNameContainsTrailingWhitespace {
            get {
                return ResourceManager.GetString("Msg_ServiceNameContainsTrailingWhitespace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name cannot begin or end with a period..
        /// </summary>
        public static string Msg_ServiceNameLeadingTrailingDot {
            get {
                return ResourceManager.GetString("Msg_ServiceNameLeadingTrailingDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name exceeds {0} characters..
        /// </summary>
        public static string Msg_ServiceNameLengthReached {
            get {
                return ResourceManager.GetString("Msg_ServiceNameLengthReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service name is required..
        /// </summary>
        public static string Msg_ServiceNameRequired {
            get {
                return ResourceManager.GetString("Msg_ServiceNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is a name reserved by Windows and cannot be used in a service name..
        /// </summary>
        public static string Msg_ServiceNameReservedDeviceName {
            get {
                return ResourceManager.GetString("Msg_ServiceNameReservedDeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified service was not found..
        /// </summary>
        public static string Msg_ServiceNotFound {
            get {
                return ResourceManager.GetString("Msg_ServiceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was removed successfully..
        /// </summary>
        public static string Msg_ServiceRemoved {
            get {
                return ResourceManager.GetString("Msg_ServiceRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was restarted successfully..
        /// </summary>
        public static string Msg_ServiceRestarted {
            get {
                return ResourceManager.GetString("Msg_ServiceRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was started successfully..
        /// </summary>
        public static string Msg_ServiceStarted {
            get {
                return ResourceManager.GetString("Msg_ServiceStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service was stopped successfully..
        /// </summary>
        public static string Msg_ServiceStopped {
            get {
                return ResourceManager.GetString("Msg_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startup error: {0}.
        /// </summary>
        public static string Msg_StartupError_Format {
            get {
                return ResourceManager.GetString("Msg_StartupError_Format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred..
        /// </summary>
        public static string Msg_UnexpectedError {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error occurred in the interface, but the application will attempt to continue. Details have been logged..
        /// </summary>
        public static string Msg_UnexpectedError_Body {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError_Body", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Servy - Unexpected Error.
        /// </summary>
        public static string Msg_UnexpectedError_Title {
            get {
                return ResourceManager.GetString("Msg_UnexpectedError_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown XML attribute encountered: &apos;{0}&apos;..
        /// </summary>
        public static string Msg_UnknownXmlAttribute {
            get {
                return ResourceManager.GetString("Msg_UnknownXmlAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown XML element encountered: &apos;{0}&apos;..
        /// </summary>
        public static string Msg_UnknownXmlElement {
            get {
                return ResourceManager.GetString("Msg_UnknownXmlElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill in all required fields..
        /// </summary>
        public static string Msg_ValidationError {
            get {
                return ResourceManager.GetString("Msg_ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation passed for service &apos;{0}&apos;..
        /// </summary>
        public static string Msg_ValidationPassed {
            get {
                return ResourceManager.GetString("Msg_ValidationPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select process executable.
        /// </summary>
        public static string Title_SelectExecutable {
            get {
                return ResourceManager.GetString("Title_SelectExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select JSON file.
        /// </summary>
        public static string Title_SelectJson {
            get {
                return ResourceManager.GetString("Title_SelectJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select startup directory.
        /// </summary>
        public static string Title_SelectStartupDirectory {
            get {
                return ResourceManager.GetString("Title_SelectStartupDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select XML file.
        /// </summary>
        public static string Title_SelectXml {
            get {
                return ResourceManager.GetString("Title_SelectXml", resourceCulture);
            }
        }
    }
}
