<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <PropertyGroup>
    <AssemblyTitle>Servy.CLI.IntegrationTests</AssemblyTitle>
    <Description>Servy.CLI integration tests</Description>
    <Product>Servy.CLI.IntegrationTests</Product>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\Servy.CLI\Servy.CLI.csproj" />
    <ProjectReference Include="..\..\src\Servy.Core\Servy.Core.csproj" />
    <ProjectReference Include="..\Servy.Testing\Servy.Testing.csproj" />
  </ItemGroup>

</Project>
