using Moq;
using Servy.Manager.Models;
using Servy.Manager.Services;
using Servy.Manager.ViewModels;
using Servy.Manager.Views;
using Servy.Testing;
using Servy.UI.Services;
using System.Windows;

namespace Servy.Manager.UnitTests.Views
{
    /// <summary>
    /// A simple concrete implementation of the abstract ServiceSearchUserControl
    /// used to safely isolate and test the shared baseline behavior.
    /// </summary>
    public class TestServiceSearchUserControl : ServiceSearchUserControl
    {
        public const string ExpectedViewName = "TestSearchView";

        protected override string ViewName => ExpectedViewName;
    }

    [Collection(AmbientTestCollection.Name)]
    public class ServiceSearchUserControlTests
    {
        /// <summary>
        /// Concrete View-Model stub inheriting from ServiceSearchViewModelBase to serve as DataContext.
        /// Correctly forwards mock dependencies to the base class and adheres to BulkObservableCollection rules.
        /// </summary>
        private class TestServiceSearchViewModel : ServiceSearchViewModelBase
        {
            public bool ExecuteAsyncWasCalled { get; private set; }
            public TaskCompletionSource<object?> CommandTcs { get; } = new TaskCompletionSource<object?>();

            public TestServiceSearchViewModel(
                ICursorService cursorService,
                IUiDispatcher uiDispatcher,
                IServiceCommands serviceCommands)
                : base(cursorService, uiDispatcher, serviceCommands)
            {
                // Override the default SearchCommand generated by the base constructor
                // to monitor execution branches inside our unit tests
                SearchCommand = new UI.Commands.AsyncCommand(async (param) =>
                {
                    ExecuteAsyncWasCalled = true;
                    await CommandTcs.Task;
                }, name: "TestSearchCommand");
            }

            /// <summary>
            /// Test seam allowing unit tests to directly set the <see cref="SearchableViewModelBase.HasSearched"/> state.
            /// </summary>
            public void SetHasSearched(bool value)
            {
                HasSearched = value;
            }

            /// <summary>
            /// Simple mock implementation of the required abstract base map routine.
            /// </summary>
            protected override ServiceItemBase CreateServiceItem(Service? service)
            {
                return new DependencyService { Name = service?.Name };
            }
        }

        private readonly Mock<ICursorService> _mockCursorService = new Mock<ICursorService>();
        private readonly Mock<IUiDispatcher> _mockUiDispatcher = new Mock<IUiDispatcher>();
        private readonly Mock<IServiceCommands> _mockServiceCommands = new Mock<IServiceCommands>();

        private TestServiceSearchViewModel CreateIsolatedViewModel()
        {
            return new TestServiceSearchViewModel(
                _mockCursorService.Object,
                _mockUiDispatcher.Object,
                _mockServiceCommands.Object);
        }

        [Fact]
        public async Task UserControl_Loaded_WhenDataContextIsNull_DoesNotThrowAndCompletesSilently()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                control.DataContext = null;

                // Act & Assert
                var exception = Record.Exception(() =>
                    control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent)));

                Assert.Null(exception);

                // Record.Exception only observes a synchronous throw. The "CompletesSilently" half of
                // the name lives in the task UiTaskRunner started, so await the seam and pin its
                // terminal state, exactly as the two exception-path tests below do.
                var task = control.LastLoadedTask;
                Assert.NotNull(task);
                await task;

                Assert.Equal(TaskStatus.RanToCompletion, task.Status);
            }, createApp: true);
        }

        [Fact]
        public async Task UserControl_Loaded_WhenServicesAlreadyExist_SkipsRedundantSearchCommandExecution()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                var viewModel = CreateIsolatedViewModel();

                // Add a dummy entry and mark HasSearched = true to represent an already-populated, searched view model
                viewModel.Services.Add(new DependencyService { Name = "ExistingService" });
                viewModel.SetHasSearched(true); // Or viewModel.HasSearched = true if setter is accessible

                control.DataContext = viewModel;

                // Act
                control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent));

                if (control.LastLoadedTask != null)
                {
                    await control.LastLoadedTask;
                }

                // Assert
                Assert.False(viewModel.ExecuteAsyncWasCalled);
            }, createApp: true);
        }

        [Fact]
        public async Task UserControl_Loaded_WhenServicesAreEmpty_ExecutesInitialSearchCommandSuccessfully()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                var viewModel = CreateIsolatedViewModel();

                viewModel.Services.Clear(); // Collection state evaluates to !Any()
                control.DataContext = viewModel;

                // Act
                control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent));
                viewModel.CommandTcs.SetResult(null);

                // ExecuteAsyncWasCalled is set on the synchronous portion of the call chain, so it is
                // already true when RaiseEvent returns and proves only that the delegate was entered.
                // Await the seam for the "Successfully" half.
                var task = control.LastLoadedTask;
                Assert.NotNull(task);
                await task;

                // Assert
                Assert.True(viewModel.ExecuteAsyncWasCalled);
                Assert.Equal(TaskStatus.RanToCompletion, task.Status);
            }, createApp: true);
        }

        [Fact]
        public async Task UserControl_Loaded_WhenOperationIsCanceled_CatchesExceptionAndHandlesGracefully()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                var viewModel = CreateIsolatedViewModel();
                control.DataContext = viewModel;

                // Act
                control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent));
                viewModel.CommandTcs.SetException(new OperationCanceledException());

                var task = control.LastLoadedTask;
                Assert.NotNull(task);
                await task;

                // Assert
                Assert.Equal(TaskStatus.RanToCompletion, task.Status);
                Assert.True(viewModel.ExecuteAsyncWasCalled);
            }, createApp: true);
        }

        [Fact]
        public async Task UserControl_Loaded_WhenGenericExceptionIsThrown_DoesNotCrashProcess()
        {
            await Helper.RunOnSTA(async () =>
            {
                // Arrange
                var control = new TestServiceSearchUserControl();
                var viewModel = CreateIsolatedViewModel();
                control.DataContext = viewModel;

                // Act
                control.RaiseEvent(new RoutedEventArgs(FrameworkElement.LoadedEvent));
                viewModel.CommandTcs.SetException(new InvalidOperationException("SCM Connection Refused"));

                var task = control.LastLoadedTask;
                Assert.NotNull(task);
                await task;

                // Assert
                Assert.Equal(TaskStatus.RanToCompletion, task.Status);
                Assert.True(viewModel.ExecuteAsyncWasCalled);
            }, createApp: true);
        }
    }
}
